// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IconIcOutlineChevronRight: typeof import('~icons/ic/outline-chevron-right')['default']
    IconIcTwotoneKeyboardArrowLeft: typeof import('~icons/ic/twotone-keyboard-arrow-left')['default']
    IconMdiArrowDownDropCircleOutline: typeof import('~icons/mdi/arrow-down-drop-circle-outline')['default']
    IconMdiArrowUpDropCircleOutline: typeof import('~icons/mdi/arrow-up-drop-circle-outline')['default']
  }
}
